# Markdownlint configuration for aiogzip
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

config:
  # Disable line length rule - technical docs often have long lines
  MD013: false

  # Allow duplicate headings with different content (common in changelogs)
  MD024:
    siblings_only: true

  # Allow inline HTML (useful for badges, etc.)
  MD033: false

  # Allow bare URLs (useful in documentation)
  MD034: false

  # Allow fenced code blocks without language (sometimes needed)
  MD040: false

  # Be more lenient with table formatting
  MD060: false
